title: Old of Tanks
description: >-
  Old of Tanks - проект возрождения WoT 10-14 годов на базе Panzer War! 
  В нем будет полноценный офлайн режим с ветками прокачки, которые не будут ссылаться к определенной версии игры. 
  Возможно добавление своей техники, либо танков, которые по тем или иным причинам планировались WG, но остались вне проекта.
baseurl: ""
url: "https://oldoftanks.github.io"

plugins:
  - jekyll-paginate-v2

pagination:
  enabled: true
  per_page: 20
  permalink: '/news/:num/'
  sort_reverse: true
  title: ':title'
  trail:
    before: 1
    after: 1

autopages:
  enabled: true
  categories:
    layouts:
      - 'paginator.html'
    permalink: '/news/:cat/'
    title: Категории
  tags:
    enabled: false
  collections:
    enabled: false

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

collections:
  dev-posts:
    output: true
  archive:
    output: true
  guide:
    output: true
  fan-pages:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: "/news/:categories/:title/"
  - scope:
      path: ""
      type: "dev-posts"
    values:
      layout: "dev-post"
      permalink: "/development/:title/"
  - scope:
      path: ""
      type: "guide"
    values:
      layout: "guidee"
      permalink: "/guide/:title/"
  - scope:
      path: ""
      type: "archive"
    values:
      layout: "archive-post"
      permalink: "/updates/:categories/:title/"
  - scope:
      path: ""
      type: "fan-pages"
    values:
      layout: "fan-page"
      permalink: "/fan-pages/:name/"
  - scope:
      path: ""
    values:
      layout: "default"